"""Write web/top_combos.js from data/top_combos.json. Run: python tools/export_top_combos.py"""
from __future__ import annotations
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "top_combos.json")
OUT = os.path.join(ROOT, "web", "top_combos.js")


def main():
    with open(SRC, encoding="utf-8") as f:
        data = json.load(f)
    js = "// AUTO-GENERATED by export_top_combos.py — sim-ranked parties for playtesting\n"
    js += "const TOP_COMBOS=" + json.dumps(
        {k: v for k, v in data.items() if k.isdigit()}, indent=2
    ) + ";\n"
    meta = data.get("meta", {})
    js += "const TOP_COMBOS_META=" + json.dumps(meta, indent=2) + ";\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)
    for p in ("2", "3", "4"):
        n = len(data[p])
        best = data[p][0]
        print(f"  {p}p: {n} combos, default {best['classes']} ({best['winrate']}%)")


if __name__ == "__main__":
    main()
