// AUTO-GENERATED by export_top_combos.py — sim-ranked parties for playtesting
const TOP_COMBOS={
  "2": [
    {
      "classes": [
        "Cleric",
        "Druid"
      ],
      "winrate": 86.0
    },
    {
      "classes": [
        "Blacksmith",
        "Cleric"
      ],
      "winrate": 83.7
    },
    {
      "classes": [
        "Cleric",
        "Ranger"
      ],
      "winrate": 77.7
    },
    {
      "classes": [
        "Bard",
        "Cleric"
      ],
      "winrate": 76.9
    },
    {
      "classes": [
        "Cleric",
        "Wizard"
      ],
      "winrate": 76.8
    },
    {
      "classes": [
        "Cleric",
        "Weaponmaster"
      ],
      "winrate": 73.9
    },
    {
      "classes": [
        "Cleric",
        "Paladin"
      ],
      "winrate": 70.8
    },
    {
      "classes": [
        "Bard",
        "Druid"
      ],
      "winrate": 56.3
    },
    {
      "classes": [
        "Cleric",
        "Enchanter"
      ],
      "winrate": 54.6
    },
    {
      "classes": [
        "Bard",
        "Paladin"
      ],
      "winrate": 37.2
    }
  ],
  "3": [
    {
      "classes": [
        "Bard",
        "Cleric",
        "Druid"
      ],
      "winrate": 98.6
    },
    {
      "classes": [
        "Cleric",
        "Druid",
        "Paladin"
      ],
      "winrate": 96.6
    },
    {
      "classes": [
        "Bard",
        "Blacksmith",
        "Cleric"
      ],
      "winrate": 96.1
    },
    {
      "classes": [
        "Bard",
        "Cleric",
        "Ranger"
      ],
      "winrate": 96.1
    },
    {
      "classes": [
        "Blacksmith",
        "Cleric",
        "Druid"
      ],
      "winrate": 95.7
    },
    {
      "classes": [
        "Bard",
        "Cleric",
        "Weaponmaster"
      ],
      "winrate": 95.5
    },
    {
      "classes": [
        "Bard",
        "Cleric",
        "Paladin"
      ],
      "winrate": 94.9
    },
    {
      "classes": [
        "Cleric",
        "Druid",
        "Weaponmaster"
      ],
      "winrate": 94.8
    },
    {
      "classes": [
        "Blacksmith",
        "Cleric",
        "Paladin"
      ],
      "winrate": 93.1
    },
    {
      "classes": [
        "Bard",
        "Cleric",
        "Enchanter"
      ],
      "winrate": 89.7
    }
  ],
  "4": [
    {
      "classes": [
        "Bard",
        "Cleric",
        "Druid",
        "Paladin"
      ],
      "winrate": 97.2
    },
    {
      "classes": [
        "Bard",
        "Blacksmith",
        "Cleric",
        "Druid"
      ],
      "winrate": 96.1
    },
    {
      "classes": [
        "Bard",
        "Cleric",
        "Druid",
        "Ranger"
      ],
      "winrate": 95.7
    },
    {
      "classes": [
        "Bard",
        "Cleric",
        "Druid",
        "Weaponmaster"
      ],
      "winrate": 95.3
    },
    {
      "classes": [
        "Bard",
        "Cleric",
        "Druid",
        "Wizard"
      ],
      "winrate": 94.6
    },
    {
      "classes": [
        "Cleric",
        "Druid",
        "Paladin",
        "Ranger"
      ],
      "winrate": 92.2
    },
    {
      "classes": [
        "Blacksmith",
        "Cleric",
        "Druid",
        "Paladin"
      ],
      "winrate": 92.1
    },
    {
      "classes": [
        "Bard",
        "Cleric",
        "Ranger",
        "Wizard"
      ],
      "winrate": 91.8
    },
    {
      "classes": [
        "Bard",
        "Blacksmith",
        "Cleric",
        "Paladin"
      ],
      "winrate": 91.3
    },
    {
      "classes": [
        "Blacksmith",
        "Cleric",
        "Druid",
        "Ranger"
      ],
      "winrate": 88.3
    }
  ]
};
const TOP_COMBOS_META={
  "source": "rank_combos.py phase-1 (100 games) + phase-2 confirm (1000 games each)",
  "config": "TUNED boss 40+10P, village 20+10P, class-fitting strategies",
  "updated": "2026-06-17"
};
